include:
  - template: Code-Quality.gitlab-ci.yml

image: python:3
stages:
  - code quality
  - build

variables:
  DOCKER_HUB_REPO: "hedius/bfacpcloudflaresync"

flake8:
  stage: code quality
  tags:
    - docker
  script:
    - python -m pip install flake8
    - flake8 --max-line-length 120 src

code_quality:
  stage: code quality


# Pylama:
#  stage: code quality
#  tags:
#    - docker
#  script:
#    - python -m pip install pylama
#    - pylama src

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        TAG="latest"
      else
        TAG="$CI_COMMIT_TAG"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$TAG" -t "$DOCKER_HUB_REPO:$TAG" .
    - docker push $CI_REGISTRY_IMAGE:$TAG
    - docker push $DOCKER_HUB_REPO:$TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
